- platform: template
  sensors:
    motor_state:
      friendly_name: "Motor State"
      value_template: >
        {% if is_state('switch.downstairs_motor_switch_1', 'on') %}
          Downstairs
        {% elif is_state('switch.upstairs_motor', 'on') %}
          Upstairs
        {% elif is_state('switch.sonoff_1000f38ea4', 'on') %}
          TankFull
        {% else %}
          MotorsOff
        {% endif %}